---
- name: minio-host1
  group: "[minio]"
  box: oravirt/ol65
  ip: 192.168.1.154

- name: minio-host2
  group: "[minio]"
  box: oravirt/ol65
  ip: 192.168.1.155

- name: minio-host3
  group: "[minio]"
  box: oravirt/ol65
  ip: 192.168.1.156

- name: minio-host4
  group: "[minio]"
  box: oravirt/ol65
  ip: 192.168.1.157