---
 - hosts: all
   sudo: yes
   remote_user: root
   gather_facts: no
   pre_tasks:
     - name: 'install python2'
       raw: sudo apt-get -y install python

 - hosts: all
   sudo: yes
   remote_user: root
   pre_tasks:
     - name: Pushes user's rsa key to root's vagrant box
       copy:
         src: ~/.ssh/id_rsa.pub
         dest: /root/.ssh/authorized_keys
         owner: root
         mode: 0600

 - name: Install and configure nginx
   hosts: all
   user: vagrant
   sudo: yes
   roles:
      - nginx

 - name: Install and configure minio
   hosts: all
   user: vagrant
   sudo: yes
   roles:
      - minio

